# on:
#   pull_request:
#     branches:
#       - main
#       - master
#   push:
#     branches:
#       - main
#       - master
#       - develop
# name: "Build & Release"
# jobs:
#   build:
#     name: Build & Release
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-java@v3
#         with:
#           java-version: '17.x'
#       - uses: subosito/flutter-action@v2
#         with:
#           flutter-version: '3.0.0'
#           channel: 'stable'
     
#       - run: flutter pub get
#       - run: flutter test
 
#       - run: flutter build apk --debug 
#       # - name: Upload Android Debug
#       #   uses: actions/upload-artifact@v2
#       #   with:
#       #     name: android-release
#       #     path: build/app/outputs/bundle/release/app-release.apk
#         # uses: andrew/release-action@v3
#         # with:
#         #   artifacts: "build/app/outputs/apk/debug/*"
#         #   tag: v1.0.${{ github.run_number }}
#         #   token: ${{ secrets.TOKEN }}






# # push to master, main, develop
# # pull request on main master

on:
 push:
    tags:
      - '*'

name: Test, Build and Release apk

env:
  JAVA_VERSION: "17.x"
  FLUTTER_VERSION: "3.0.5"
  FLUTTER_CHANNEL: "stable"


jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{env.JAVA_VERSION}}
    - uses: subosito/flutter-action@v1
      with:
        channel: ${{env.FLUTTER_CHANNEL}}
        flutter-version: ${{env.FLUTTER_VERSION}}
    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        channel: stable
        version: '3.0.5'  
    - run: flutter doctor -v
    - run: flutter upgrade
    - run: flutter doctor -v
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.TOKEN }}