on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'
          channel: 'stable'
      - name: Get dependencies
      - run: flutter pub get
      - run: flutter test
      - name: Start release build
      - run: flutter build apk --debug 
      - name: Upload Android Debug
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: build/app/outputs/bundle/release/app-release.apk
        # uses: andrew/release-action@v3
        # with:
        #   artifacts: "build/app/outputs/apk/debug/*"
        #   tag: v1.0.${{ github.run_number }}
        #   token: ${{ secrets.TOKEN }}






# push to master, main, develop
# pull request on main master