# on:
#   pull_request:
#     branches:
#       - main
#       - master
#   push:
#     branches:
#       - main
#       - master
#       - develop
# name: "Build & Release"
# jobs:
#   build:
#     name: Build & Release
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-java@v3
#         with:
#           java-version: '17.x'
#       - uses: subosito/flutter-action@v2
#         with:
#           flutter-version: '3.0.0'
#           channel: 'stable'
     
#       - run: flutter pub get
#       - run: flutter test
 
#       - run: flutter build apk --debug 
#       # - name: Upload Android Debug
#       #   uses: actions/upload-artifact@v2
#       #   with:
#       #     name: android-release
#       #     path: build/app/outputs/bundle/release/app-release.apk
#         # uses: andrew/release-action@v3
#         # with:
#         #   artifacts: "build/app/outputs/apk/debug/*"
#         #   tag: v1.0.${{ github.run_number }}
#         #   token: ${{ secrets.TOKEN }}






# # push to master, main, develop
# # pull request on main master

on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dart-lang/setup-dart@v1
      with:
        dart-version: '3.0.5'
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.TOKEN }}